[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = ["python3 -m pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "cd Login && python3 -m gunicorn wsgi:application --bind 0.0.0.0:$PORT --workers 2"

